spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nft?serverTimezone=UTC&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: com.atguigu.admin.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）


  jdbc:
    template:
      query-timeout: 3

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

